### ISSUE TITLE
Add SiFive Custom Extensions Support

### ISSUE THREAD

**Issue by nschwass** [drom/rv#24]
SiFive has recently published three specifications for our custom extensions listed below. This issue requests that we add support for those extensions. Documents are listed below.

Xsfvqmaccqoq Extension Int8 Matrix Multiplication (4-by-8 and 8-by-4) + Xsfvqmaccdod Int8 Matrix Multiplication Instructions (2-by-8 and 8-by-2)
https://sifive.cdn.prismic.io/sifive/60d5a660-3af0-49a3-a904-d2bbb1a21517_int8-matmul-spec.pdf

Xsfvfnrclipxfqf FP32-to-int8 Ranged Clip Instructions Extension 
https://sifive.cdn.prismic.io/sifive/0aacff47-f530-43dc-8446-5caa2260ece0_xsfvfnrclipxfqf-spec.pdf

Xsfvfwmaccqqq Matrix Multiply Accumulate Instruction Extension Specification
https://sifive.cdn.prismic.io/sifive/c391d53e-ffcf-4091-82f6-c37bf3e883ed_xsfvfwmaccqqq-spec.pdf

**Comment by drom** [comment]
@nschwass fixed. please try: https://rv.drom.io/?rv64i2p1ma2p1f2p2d2p2c_zifencei_zk_zvkn_zvks_Sv39_zVe64f1_sscofpmf0p1_Xsfvqmaccqoq_Xsfvqmaccdod_Xsfvfnrclipxfqf_Xsfvfwmaccqqq
